services:
  - type: worker
    name: autogpt-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
